// Generated by gencpp from file experimental_ass/string_message.msg
// DO NOT EDIT!


#ifndef EXPERIMENTAL_ASS_MESSAGE_STRING_MESSAGE_H
#define EXPERIMENTAL_ASS_MESSAGE_STRING_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace experimental_ass
{
template <class ContainerAllocator>
struct string_message_
{
  typedef string_message_<ContainerAllocator> Type;

  string_message_()
    : custom_msg()  {
    }
  string_message_(const ContainerAllocator& _alloc)
    : custom_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _custom_msg_type;
  _custom_msg_type custom_msg;





  typedef boost::shared_ptr< ::experimental_ass::string_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::experimental_ass::string_message_<ContainerAllocator> const> ConstPtr;

}; // struct string_message_

typedef ::experimental_ass::string_message_<std::allocator<void> > string_message;

typedef boost::shared_ptr< ::experimental_ass::string_message > string_messagePtr;
typedef boost::shared_ptr< ::experimental_ass::string_message const> string_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::experimental_ass::string_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::experimental_ass::string_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::experimental_ass::string_message_<ContainerAllocator1> & lhs, const ::experimental_ass::string_message_<ContainerAllocator2> & rhs)
{
  return lhs.custom_msg == rhs.custom_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::experimental_ass::string_message_<ContainerAllocator1> & lhs, const ::experimental_ass::string_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace experimental_ass

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::experimental_ass::string_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::experimental_ass::string_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::experimental_ass::string_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::experimental_ass::string_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::experimental_ass::string_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::experimental_ass::string_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::experimental_ass::string_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34bc0b7b6938cfa2480828862cdaf1a1";
  }

  static const char* value(const ::experimental_ass::string_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34bc0b7b6938cfa2ULL;
  static const uint64_t static_value2 = 0x480828862cdaf1a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::experimental_ass::string_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "experimental_ass/string_message";
  }

  static const char* value(const ::experimental_ass::string_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::experimental_ass::string_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string custom_msg\n"
;
  }

  static const char* value(const ::experimental_ass::string_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::experimental_ass::string_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.custom_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct string_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::experimental_ass::string_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::experimental_ass::string_message_<ContainerAllocator>& v)
  {
    s << indent << "custom_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.custom_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPERIMENTAL_ASS_MESSAGE_STRING_MESSAGE_H
